# Generated by Django 3.2.13 on 2024-02-10 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('like', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='is_anonymous',
        ),
    ]
