services:
  web:
    image: whoamitoday/whoamitoday-backend:latest
    working_dir: /app/adoorback
    ports:
      - "80:8000"
      - "443:8000" # HTTPS
    env_file:
      - .env
    depends_on:
      - db
    command: >
      sh -c '
      sleep 5 &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000
      '
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1G
    restart: unless-stopped

  db:
    image: postgres:13
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 30s
      timeout: 10s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 2G
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
