version: "3.8"
services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env.development
    environment:
      - DJANGO_ENV=development
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy # ✅ DB가 정상 실행될 때까지 대기
    command: /app/start.sh

  db:
    image: postgres:13
    env_file:
      - .env.development
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck: # ✅ PostgreSQL 상태 확인
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5
      start_period: 5s

volumes:
  postgres_data:
    driver: local
