FROM whoami-today-backend-web:latest AS base

USER root

# cron 패키지만 추가 설치
RUN apt-get update && apt-get install -y cron && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY ./cron/crontab_jobs /etc/cron.d/crontab_jobs
RUN chmod 0644 /etc/cron.d/crontab_jobs
RUN crontab /etc/cron.d/crontab_jobs

CMD ["cron", "-f"]
