# Generated by Django 4.2.14 on 2025-01-17 06:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_id', models.IntegerField(null=True)),
                ('origin_id', models.IntegerField(null=True)),
                ('redirect_url', models.CharField(max_length=150)),
                ('message', models.CharField(max_length=100)),
                ('message_ko', models.CharField(max_length=100, null=True)),
                ('message_en', models.CharField(max_length=100, null=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('is_read', models.BooleanField(default=False)),
                ('notification_updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'ordering': ['-notification_updated_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationActor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notification.notification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='actors',
            field=models.ManyToManyField(related_name='sent_notification_set', through='notification.NotificationActor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='origin_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origin_noti_set', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='notification',
            name='target_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='targetted_noti_set', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_noti_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['-notification_updated_at'], name='notificatio_notific_bb8886_idx'),
        ),
    ]
