# Generated by Django 3.2.13 on 2024-02-05 20:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notification', '0004_auto_20230319_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='actor',
        ),
        migrations.AddField(
            model_name='notification',
            name='actor_count',
            field=models.PositiveIntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='actors',
            field=models.ManyToManyField(related_name='sent_noti_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
