# Generated by Django 4.2.11 on 2024-03-09 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0004_remove_notification_actors"),
    ]

    operations = [
        migrations.RenameField(
            model_name="notification", old_name="new_actors", new_name="actors",
        ),
    ]
