# Generated by Django 3.2.13 on 2024-02-05 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_auto_20240205_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='actor_count',
        ),
    ]
