# Generated by Django 3.2.13 on 2024-02-05 21:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notification', '0006_remove_notification_actor_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='actors',
            field=models.ManyToManyField(null=True, related_name='sent_noti_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
