# Generated by Django 4.2.14 on 2026-05-02 01:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Mission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(max_length=64, unique=True)),
                ("prompt_en", models.TextField()),
                ("prompt_ko", models.TextField(blank=True, default="")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("song", "Song"),
                            ("question", "Question"),
                            ("text", "Text"),
                            ("compliment", "Compliment"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "selected_dates",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.DateField(),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("selected", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
