# Generated by Django 4.2.14 on 2026-04-30 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Survey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(max_length=64, unique=True)),
                ("title", models.CharField(max_length=200)),
                ("title_ko", models.CharField(max_length=200, null=True)),
                ("title_en", models.CharField(max_length=200, null=True)),
                ("description", models.TextField(blank=True, default="")),
                ("description_ko", models.TextField(blank=True, default="", null=True)),
                ("description_en", models.TextField(blank=True, default="", null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("likert_5", "Likert 5-point"),
                            ("single_choice", "Single choice"),
                            ("multi_choice", "Multi choice"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "interpretation",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text='Markdown shown after results unlock (e.g., "Higher scores indicate ...")',
                    ),
                ),
                (
                    "interpretation_ko",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text='Markdown shown after results unlock (e.g., "Higher scores indicate ...")',
                        null=True,
                    ),
                ),
                (
                    "interpretation_en",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text='Markdown shown after results unlock (e.g., "Higher scores indicate ...")',
                        null=True,
                    ),
                ),
                (
                    "last_used_date",
                    models.DateField(
                        blank=True,
                        db_index=True,
                        help_text="Date this Survey was last scheduled by RotateDailySurveyCronJob.",
                        null=True,
                    ),
                ),
            ],
            options={
                "ordering": ["slug"],
            },
        ),
        migrations.CreateModel(
            name="SurveyResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "submitted_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="surveys.survey",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="survey_responses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SurveyQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("order", models.PositiveSmallIntegerField()),
                ("prompt", models.TextField()),
                ("prompt_ko", models.TextField(null=True)),
                ("prompt_en", models.TextField(null=True)),
                ("low_label", models.CharField(blank=True, default="", max_length=80)),
                (
                    "low_label_ko",
                    models.CharField(blank=True, default="", max_length=80, null=True),
                ),
                (
                    "low_label_en",
                    models.CharField(blank=True, default="", max_length=80, null=True),
                ),
                ("high_label", models.CharField(blank=True, default="", max_length=80)),
                (
                    "high_label_ko",
                    models.CharField(blank=True, default="", max_length=80, null=True),
                ),
                (
                    "high_label_en",
                    models.CharField(blank=True, default="", max_length=80, null=True),
                ),
                ("reverse_scored", models.BooleanField(default=False)),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="surveys.survey",
                    ),
                ),
            ],
            options={
                "ordering": ["survey_id", "order"],
            },
        ),
        migrations.CreateModel(
            name="SurveyOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("order", models.PositiveSmallIntegerField()),
                ("label", models.CharField(max_length=160)),
                ("label_ko", models.CharField(max_length=160, null=True)),
                ("label_en", models.CharField(max_length=160, null=True)),
                (
                    "value",
                    models.IntegerField(
                        help_text="Numeric value used for scoring (likert) or option id (choice)."
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="surveys.surveyquestion",
                    ),
                ),
            ],
            options={
                "ordering": ["question_id", "order"],
            },
        ),
        migrations.CreateModel(
            name="SurveyAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "value",
                    models.JSONField(
                        help_text="Integer for likert/single, list of integers for multi."
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="answers",
                        to="surveys.surveyquestion",
                    ),
                ),
                (
                    "response",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="surveys.surveyresponse",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DailySurvey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField(unique=True)),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scheduled_days",
                        to="surveys.survey",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.AddIndex(
            model_name="surveyresponse",
            index=models.Index(
                fields=["survey", "user"], name="surveys_sur_survey__773590_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="surveyresponse",
            constraint=models.UniqueConstraint(
                fields=("user", "survey"), name="unique_response_per_user_per_survey"
            ),
        ),
        migrations.AddConstraint(
            model_name="surveyquestion",
            constraint=models.UniqueConstraint(
                fields=("survey", "order"), name="unique_question_order_per_survey"
            ),
        ),
        migrations.AddConstraint(
            model_name="surveyoption",
            constraint=models.UniqueConstraint(
                fields=("question", "order"), name="unique_option_order_per_question"
            ),
        ),
        migrations.AddConstraint(
            model_name="surveyanswer",
            constraint=models.UniqueConstraint(
                fields=("response", "question"),
                name="unique_answer_per_response_per_question",
            ),
        ),
    ]
