# Generated by Django 4.2.14 on 2026-05-01 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="survey",
            name="type",
        ),
        migrations.AddField(
            model_name="survey",
            name="friend_visible",
            field=models.BooleanField(
                default=True,
                help_text="Survey-level kill switch for friend / close-friend buckets across all panels. Individual panels may still be suppressed when their kind is wordcloud-style.",
            ),
        ),
        migrations.AddField(
            model_name="survey",
            name="results_hidden",
            field=models.BooleanField(
                default=False,
                help_text="If True, this survey accepts responses but the results endpoint always 404s.",
            ),
        ),
        migrations.AddField(
            model_name="surveyquestion",
            name="result_group",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Group key — questions sharing a non-empty group are aggregated into a single panel. Blank → grouped implicitly with sibling questions of the same type.",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="surveyquestion",
            name="result_hidden",
            field=models.BooleanField(
                default=False,
                help_text="If True, this question is answered but never appears on the results page.",
            ),
        ),
        migrations.AddField(
            model_name="surveyquestion",
            name="result_kind",
            field=models.CharField(
                blank=True,
                choices=[
                    ("aggregated_likert", "Aggregated likert score"),
                    ("option_counts", "Per-option counts"),
                    ("wordcloud", "Wordcloud (free-text tokens)"),
                ],
                default="",
                help_text="Override the default renderer for this question. Blank → derived from `type`.",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="surveyquestion",
            name="type",
            field=models.CharField(
                choices=[
                    ("likert_5", "Likert 5-point"),
                    ("single_choice", "Single choice"),
                    ("multi_choice", "Multi choice"),
                    ("free_text", "Free text"),
                ],
                default="likert_5",
                help_text="Input type. Determines which input UI is rendered and how value is validated.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="surveyanswer",
            name="value",
            field=models.JSONField(
                help_text="Shape depends on question.type: int for likert/single, list[int] for multi, str for free_text."
            ),
        ),
    ]
