# Generated by Django 4.2.14 on 2026-05-01 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0002_remove_survey_type_survey_friend_visible_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduledSurvey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cadence",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("biweekly", "Biweekly"),
                            ("anytime", "Anytime"),
                            ("endpoint", "Endpoint"),
                        ],
                        max_length=16,
                    ),
                ),
                ("window_start", models.DateField()),
                ("window_end", models.DateField(blank=True, null=True)),
                ("allow_late", models.BooleanField(default=True)),
                ("sequence_index", models.PositiveSmallIntegerField()),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="surveys.survey",
                    ),
                ),
            ],
            options={
                "ordering": ["window_start", "sequence_index"],
            },
        ),
        migrations.AddConstraint(
            model_name="scheduledsurvey",
            constraint=models.UniqueConstraint(
                fields=("cadence", "sequence_index"),
                name="unique_scheduled_survey_cadence_seq",
            ),
        ),
    ]
