# Generated by Django 4.2.14 on 2026-05-01 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0004_seed_study_schedule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="survey",
            name="last_used_date",
            field=models.DateField(
                blank=True,
                db_index=True,
                help_text="Legacy field — written by the now-deleted rotation cron. Unused.",
                null=True,
            ),
        ),
        migrations.DeleteModel(
            name="DailySurvey",
        ),
    ]
