# Generated by Django 4.2.14 on 2026-05-01 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0005_alter_survey_last_used_date_delete_dailysurvey"),
    ]

    operations = [
        migrations.AddField(
            model_name="surveyquestion",
            name="slider_max_value",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="surveyquestion",
            name="slider_min_value",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="surveyquestion",
            name="result_kind",
            field=models.CharField(
                blank=True,
                choices=[
                    ("aggregated_likert", "Aggregated likert score"),
                    ("option_counts", "Per-option counts"),
                    ("wordcloud", "Wordcloud (free-text tokens)"),
                    ("slider_histogram", "Slider histogram"),
                ],
                default="",
                help_text="Override the default renderer for this question. Blank → derived from `type`.",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="surveyquestion",
            name="type",
            field=models.CharField(
                choices=[
                    ("likert_5", "Likert 5-point"),
                    ("single_choice", "Single choice"),
                    ("multi_choice", "Multi choice"),
                    ("free_text", "Free text"),
                    ("slider", "Slider"),
                ],
                default="likert_5",
                help_text="Input type. Determines which input UI is rendered and how value is validated.",
                max_length=20,
            ),
        ),
    ]
