# Generated by Django 4.2.14 on 2026-05-04 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("surveys", "0006_surveyquestion_slider_max_value_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSurveyEmbeddedData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.CharField(max_length=80)),
                ("value", models.JSONField()),
            ],
        ),
        migrations.AddField(
            model_name="survey",
            name="repeatable",
            field=models.BooleanField(
                default=False,
                help_text="When True, the same user may submit this survey multiple times within its window. Each submission is a separate SurveyResponse row. Used for anytime_reflection-style ongoing feedback surveys.",
            ),
        ),
        migrations.AddField(
            model_name="survey",
            name="result_kind",
            field=models.CharField(
                blank=True,
                choices=[
                    ("aggregated_likert", "Aggregated likert score"),
                    ("option_counts", "Per-option counts"),
                    ("wordcloud", "Wordcloud (free-text tokens)"),
                    ("slider_histogram", "Slider histogram"),
                    (
                        "scale_score_histogram",
                        "Scale-score histogram (survey-level summary)",
                    ),
                    ("slider_histogram_paired", "Paired-slider 2D circumplex"),
                ],
                default="",
                help_text="Optional whole-survey result renderer. When set, overrides the per-question result_kind on the results page (e.g. scale_score_histogram for a single summary score across all items).",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="survey",
            name="score_components",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Optional list of question slugs to include in scale_score_histogram scoring. Empty list = include every likert_* item in the survey.",
            ),
        ),
        migrations.AddField(
            model_name="survey",
            name="score_formula",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Name of a registered formula in surveys/scoring/registry.py. When blank, scale_score_histogram falls back to the default sum-with-reverse formula. See `surveys.scoring.registry.score_formulas`.",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="survey",
            name="serving_condition",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Optional rule for skipping this survey for specific users. Form: {"skip_if_user_embedded_data": {"<key>": <value>, ...}}. When all key/value pairs match the user\'s embedded data, the survey is not served to that user.',
            ),
        ),
        migrations.AddField(
            model_name="survey",
            name="tokens",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Static token map substituted into prompts/descriptions/placeholders at render time via {{token_name}}. e.g. {"phase_label": "Phase 1"}.',
            ),
        ),
        migrations.AddField(
            model_name="surveyquestion",
            name="conditional_display",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Rule for showing this question based on a prior answer in the same submission.",
            ),
        ),
        migrations.AddField(
            model_name="surveyquestion",
            name="content",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Markdown body for display_only questions. Token substitution applies.",
            ),
        ),
        migrations.AddField(
            model_name="surveyquestion",
            name="content_en",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Markdown body for display_only questions. Token substitution applies.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="surveyquestion",
            name="content_ko",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Markdown body for display_only questions. Token substitution applies.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="surveyquestion",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="surveyquestion",
            name="description_en",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="surveyquestion",
            name="description_ko",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="surveyquestion",
            name="embedded_data",
            field=models.BooleanField(
                default=False,
                help_text="If True, the answer is copied into UserSurveyEmbeddedData (keyed by slug) on submission.",
            ),
        ),
        migrations.AddField(
            model_name="surveyquestion",
            name="min_length",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="surveyquestion",
            name="min_length_warning",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Markdown shown when `min_length` is unmet. Submission still allowed after one acknowledgment.",
            ),
        ),
        migrations.AddField(
            model_name="surveyquestion",
            name="min_length_warning_en",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Markdown shown when `min_length` is unmet. Submission still allowed after one acknowledgment.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="surveyquestion",
            name="min_length_warning_ko",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Markdown shown when `min_length` is unmet. Submission still allowed after one acknowledgment.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="surveyquestion",
            name="na_option",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Label for the N/A option on likert_5_na questions. Empty string suppresses the N/A choice.",
                max_length=80,
            ),
        ),
        migrations.AddField(
            model_name="surveyquestion",
            name="na_option_en",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Label for the N/A option on likert_5_na questions. Empty string suppresses the N/A choice.",
                max_length=80,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="surveyquestion",
            name="na_option_ko",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Label for the N/A option on likert_5_na questions. Empty string suppresses the N/A choice.",
                max_length=80,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="surveyquestion",
            name="placeholder",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="surveyquestion",
            name="placeholder_en",
            field=models.CharField(blank=True, default="", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="surveyquestion",
            name="placeholder_ko",
            field=models.CharField(blank=True, default="", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="surveyquestion",
            name="required",
            field=models.BooleanField(
                default=True,
                help_text="If True, submission is blocked until this question is answered (unless conditionally hidden).",
            ),
        ),
        migrations.AddField(
            model_name="surveyquestion",
            name="slug",
            field=models.SlugField(
                blank=True,
                default="",
                help_text="Stable per-question identifier. Required for any question referenced by a score formula or conditional_display.",
                max_length=80,
            ),
        ),
        migrations.AlterField(
            model_name="surveyanswer",
            name="value",
            field=models.JSONField(
                help_text='Shape depends on question.type: int for likert/single, list[int] for multi, str for free_text. None (NA_SENTINEL) on likert_5_na means "N/A".'
            ),
        ),
        migrations.AlterField(
            model_name="surveyquestion",
            name="result_kind",
            field=models.CharField(
                blank=True,
                choices=[
                    ("aggregated_likert", "Aggregated likert score"),
                    ("option_counts", "Per-option counts"),
                    ("wordcloud", "Wordcloud (free-text tokens)"),
                    ("slider_histogram", "Slider histogram"),
                    (
                        "scale_score_histogram",
                        "Scale-score histogram (survey-level summary)",
                    ),
                    ("slider_histogram_paired", "Paired-slider 2D circumplex"),
                ],
                default="",
                help_text="Override the default renderer for this question. Blank → derived from `type`.",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="surveyquestion",
            name="type",
            field=models.CharField(
                choices=[
                    ("likert_3", "Likert 3-point"),
                    ("likert_4", "Likert 4-point"),
                    ("likert_5", "Likert 5-point"),
                    ("likert_5_na", "Likert 5-point with N/A option"),
                    ("likert_6", "Likert 6-point"),
                    ("likert_7", "Likert 7-point"),
                    ("single_choice", "Single choice"),
                    ("multi_choice", "Multi choice"),
                    ("free_text", "Free text"),
                    ("slider", "Slider"),
                    ("display_only", "Display-only content (no input)"),
                ],
                default="likert_5",
                help_text="Input type. Determines which input UI is rendered and how value is validated.",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="surveyquestion",
            constraint=models.UniqueConstraint(
                condition=models.Q(("slug", ""), _negated=True),
                fields=("survey", "slug"),
                name="unique_question_slug_per_survey",
            ),
        ),
        migrations.AddField(
            model_name="usersurveyembeddeddata",
            name="source_question",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="surveys.surveyquestion",
            ),
        ),
        migrations.AddField(
            model_name="usersurveyembeddeddata",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="survey_embedded_data",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="usersurveyembeddeddata",
            index=models.Index(
                fields=["user", "key"], name="surveys_use_user_id_99f672_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="usersurveyembeddeddata",
            constraint=models.UniqueConstraint(
                fields=("user", "key"), name="unique_embedded_data_per_user_key"
            ),
        ),
    ]
