# Generated by Django 4.2.14 on 2026-05-04 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0007_extend_schema_for_long_form_studies"),
    ]

    operations = [
        migrations.AlterField(
            model_name="surveyanswer",
            name="value",
            field=models.JSONField(
                blank=True,
                help_text='Shape depends on question.type: int for likert/single, list[int] for multi, str for free_text. NULL (NA_SENTINEL) on likert_5_na means "N/A".',
                null=True,
            ),
        ),
    ]
