# Generated by Django 4.2.14 on 2026-05-04 19:00
# Hand-edited so the integer→jsonb conversion uses to_jsonb(); Postgres has
# no implicit cast from int to jsonb.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0008_allow_null_surveyanswer_value"),
    ]

    operations = [
        # Cast existing integer values into JSON numbers via to_jsonb().
        # Django's stock AlterField generates `USING value::jsonb`, which
        # Postgres rejects (no implicit cast from int to jsonb). The custom
        # SQL below produces an equivalent ALTER with the correct cast.
        migrations.RunSQL(
            sql='ALTER TABLE "surveys_surveyoption" ALTER COLUMN "value" '
                'TYPE jsonb USING to_jsonb("value");',
            reverse_sql='ALTER TABLE "surveys_surveyoption" ALTER COLUMN "value" '
                        'TYPE integer USING ("value"#>>\'{}\')::integer;',
            state_operations=[
                migrations.AlterField(
                    model_name="surveyoption",
                    name="value",
                    field=models.JSONField(
                        help_text=(
                            "Score code (int for likert / ordinal) or category code "
                            "(string for categorical). Multi-choice answers store a "
                            "list of these values."
                        ),
                    ),
                ),
            ],
        ),
    ]
