# Generated by Django 4.2.14 on 2026-05-04 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0009_surveyoption_value_jsonfield"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="surveyresponse",
            name="unique_response_per_user_per_survey",
        ),
    ]
