# Schedule the 20 SOTD (Survey of the Day) instruments on their assigned
# weekdays of the 4-week study (May 4 - May 31, 2026).
#
# Slug convention: `sotd_dNN_*` where NN = the study day number
# (1-indexed from May 4 kickoff). Weekend study days (6, 7, 13, 14, 20,
# 21, 27, 28) have no SOTD assigned — the slug numbering already skips
# them, and `_is_weekend_skipped` defends against accidentally serving
# any future SOTD that lands on a weekend.
#
# Sequence index 100+day_number to stay clear of:
#   - daily_base    (seq 1..28, from 0004)
#   - mock dailies  (seq 900..902)
#   - demo dailies  (seq 1000..1011)
#
# `get_today_daily` is updated in this same change set to prefer SOTD
# slugs over daily_base when both are scheduled on the same date — the
# diary continues to land in the index/archive but the SOTD takes the
# Survey-of-the-Day card.
from datetime import date, timedelta

from django.db import migrations


# Same kickoff anchor as 0004 + 0011 (post +1 day shift in 0012, the
# canonical kickoff is May 4). _day(n) is 1-indexed: day 1 = May 4.
STUDY_START = date(2026, 5, 4)


def _day(n: int) -> date:
    return STUDY_START + timedelta(days=n - 1)


# (study_day_number, slug) — sequence_index will be 100 + day_number.
# Generated by reading the slug: `sotd_dNN_*` → day = NN.
SOTD_SCHEDULE = [
    (1,  'sotd_d01_honeymoon'),
    (2,  'sotd_d02_rsds'),
    (3,  'sotd_d03_iscs_bond'),
    (4,  'sotd_d04_iscs_bridge'),
    (5,  'sotd_d05_rsq'),
    # Days 6, 7 = Sat, Sun — no SOTD by spec.
    (8,  'sotd_d08_singelis_ind'),
    (9,  'sotd_d09_singelis_int'),
    (10, 'sotd_d10_woodAS'),
    (11, 'sotd_d11_ucla8'),
    (12, 'sotd_d12_ntb'),
    # Days 13, 14 = Sat, Sun — mid_study_w/q biweekly on day 14, no daily SOTD.
    (15, 'sotd_d15_shi'),
    (16, 'sotd_d16_hexaco_hh'),
    (17, 'sotd_d17_hexaco_em'),
    (18, 'sotd_d18_hexaco_ex'),
    (19, 'sotd_d19_hexaco_ag'),
    # Days 20, 21 = Sat, Sun — no SOTD.
    (22, 'sotd_d22_hexaco_co'),
    (23, 'sotd_d23_hexaco_op'),
    (24, 'sotd_d24_ceii'),
    (25, 'sotd_d25_iuipc'),
    (26, 'sotd_d26_transition'),
    # Days 27, 28 = Sat, Sun — post_study_w/q biweekly on day 28, no daily SOTD.
]


def seed_sotd_schedule(apps, schema_editor):
    """Schedule each SOTD on its assigned study day.

    Idempotent — `update_or_create` keyed on (cadence, sequence_index).
    Short-circuits silently if Surveys are missing (matches 0004 / 0011).
    """
    Survey = apps.get_model('surveys', 'Survey')
    ScheduledSurvey = apps.get_model('surveys', 'ScheduledSurvey')
    if not Survey.objects.exists():
        return

    for day_n, slug in SOTD_SCHEDULE:
        try:
            survey = Survey.objects.get(slug=slug)
        except Survey.DoesNotExist:
            # Slug not loaded yet — setup_survey_state will retry next run.
            continue
        ScheduledSurvey.objects.update_or_create(
            cadence='daily',
            sequence_index=100 + day_n,
            defaults={
                'survey': survey,
                'window_start': _day(day_n),
                'window_end': _day(day_n),
                'allow_late': False,
            },
        )


def unseed_sotd_schedule(apps, schema_editor):
    ScheduledSurvey = apps.get_model('surveys', 'ScheduledSurvey')
    ScheduledSurvey.objects.filter(
        cadence='daily',
        sequence_index__in=[100 + n for n, _ in SOTD_SCHEDULE],
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0012_shift_study_schedule_to_may_4'),
    ]

    operations = [
        migrations.RunPython(seed_sotd_schedule, reverse_code=unseed_sotd_schedule),
    ]
