# Generated by Django 4.2.14 on 2026-05-18 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("surveys", "0019_sotd_allow_late_true"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="surveyanswer",
            name="unique_answer_per_response_per_question",
        ),
        migrations.AddField(
            model_name="surveyanswer",
            name="target_user",
            field=models.ForeignKey(
                blank=True,
                help_text="Only populated for per-friend question types. NULL for all other types. Indicates the friend that the answer's value is about.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="survey_answers_targeting",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="surveyquestion",
            name="type",
            field=models.CharField(
                choices=[
                    ("likert_3", "Likert 3-point"),
                    ("likert_4", "Likert 4-point"),
                    ("likert_5", "Likert 5-point"),
                    ("likert_5_na", "Likert 5-point with N/A option"),
                    ("likert_6", "Likert 6-point"),
                    ("likert_7", "Likert 7-point"),
                    ("single_choice", "Single choice"),
                    ("multi_choice", "Multi choice"),
                    ("free_text", "Free text"),
                    ("slider", "Slider"),
                    ("display_only", "Display-only content (no input)"),
                    ("per_friend_likert_5", "Likert 5-point asked once per friend"),
                    ("per_friend_single_choice", "Single choice asked once per friend"),
                ],
                default="likert_5",
                help_text="Input type. Determines which input UI is rendered and how value is validated.",
                max_length=32,
            ),
        ),
        migrations.AddIndex(
            model_name="surveyanswer",
            index=models.Index(
                fields=["target_user"], name="surveys_sur_target__31ebf6_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="surveyanswer",
            constraint=models.UniqueConstraint(
                condition=models.Q(("target_user__isnull", True)),
                fields=("response", "question"),
                name="unique_answer_per_response_per_question",
            ),
        ),
        migrations.AddConstraint(
            model_name="surveyanswer",
            constraint=models.UniqueConstraint(
                condition=models.Q(("target_user__isnull", False)),
                fields=("response", "question", "target_user"),
                name="unique_answer_per_response_per_question_per_target",
            ),
        ),
    ]
