# Generated by Django 4.2.14 on 2026-05-18 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0024_seed_pre_study_catchup_schedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduledsurvey",
            name="sidebar_order",
            field=models.PositiveSmallIntegerField(
                blank=True,
                default=None,
                help_text="Optional explicit order within each survey index bucket. Lower numbers appear earlier. Blank falls back to survey priority, window_start, then sequence_index.",
                null=True,
            ),
        ),
    ]
