# Generated by Django 4.2.14 on 2026-05-19 00:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("surveys", "0033_update_friend_closeness_interaction_prompt"),
    ]

    operations = [
        migrations.CreateModel(
            name="SurveyDraft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("answers", models.JSONField(blank=True, default=dict)),
                ("current_page_index", models.PositiveIntegerField(default=0)),
                ("total_pages", models.PositiveIntegerField(default=0)),
                ("answered_pages", models.PositiveIntegerField(default=0)),
                ("progress_pct", models.PositiveSmallIntegerField(default=0)),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drafts",
                        to="surveys.survey",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="survey_drafts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "survey"], name="surveys_sur_user_id_c93b46_idx"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="surveydraft",
            constraint=models.UniqueConstraint(
                fields=("user", "survey"), name="unique_survey_draft_per_user"
            ),
        ),
    ]
