# Generated by Django 4.2.14 on 2026-05-19 02:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("surveys", "0035_survey_priority_order_and_weekend_due_dates"),
    ]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="point_prereq_slug",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Slug of a survey that must be completed before this one credits its full point_value. Blank = no prereq. Submission with prereq unmet still creates a PointAward row with awarded_points=0.",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="survey",
            name="point_value",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Provisional max points credited on first submit. 0 = no points. Researcher audit at study end may downgrade individual awards.",
            ),
        ),
        migrations.CreateModel(
            name="PointAward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source_kind",
                    models.CharField(
                        choices=[
                            ("survey", "Survey response"),
                            ("wit_bot_audit", "Wit_bot audit pass"),
                            ("interview_signup", "Interview signup"),
                        ],
                        max_length=32,
                    ),
                ),
                ("source_slug", models.CharField(max_length=64)),
                ("awarded_points", models.PositiveIntegerField()),
                ("adjusted_points", models.PositiveIntegerField(blank=True, null=True)),
                ("note", models.TextField(blank=True, default="")),
                (
                    "response",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="point_awards",
                        to="surveys.surveyresponse",
                    ),
                ),
                (
                    "scheduled_survey",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="point_awards",
                        to="surveys.scheduledsurvey",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="point_awards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["user", "source_kind"],
                        name="surveys_poi_user_id_a5ae7e_idx",
                    ),
                    models.Index(
                        fields=["source_kind", "source_slug"],
                        name="surveys_poi_source__940ab9_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="pointaward",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("response__isnull", False), ("source_kind", "survey")
                ),
                fields=("user", "response"),
                name="unique_award_per_user_per_response",
            ),
        ),
        migrations.AddConstraint(
            model_name="pointaward",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("scheduled_survey__isnull", False), ("source_kind", "survey")
                ),
                fields=("user", "scheduled_survey"),
                name="unique_award_per_user_per_scheduled_survey",
            ),
        ),
        migrations.AddConstraint(
            model_name="pointaward",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("response__isnull", True), ("scheduled_survey__isnull", True)
                ),
                fields=("user", "source_kind", "source_slug"),
                name="unique_award_per_user_per_non_survey_source",
            ),
        ),
    ]
