# Generated by Django 4.2.14 on 2026-05-26 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0043_phase1_friend_closeness_noneditable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pointaward",
            name="source_kind",
            field=models.CharField(
                choices=[
                    ("survey", "Survey response"),
                    ("wit_bot_audit", "Wit_bot audit pass"),
                    ("app_usage", "App usage"),
                    ("interview_signup", "Interview signup"),
                ],
                max_length=32,
            ),
        ),
    ]
