# Generated by Django 4.2.14 on 2026-05-01 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("browse_mode", "0002_browsemodewishlistentry"),
    ]

    operations = [
        migrations.AddField(
            model_name="browsemodepreset",
            name="default_battery",
            field=models.CharField(
                blank=True,
                choices=[
                    ("completely_drained", "Completely Drained"),
                    ("low", "Low Social Battery"),
                    ("needs_recharge", "Needs Recharge"),
                    ("moderately_social", "Moderately Social"),
                    ("fully_charged", "Fully Charged"),
                    ("super_social", "Super Social Mode (HMU!)"),
                ],
                max_length=30,
                null=True,
            ),
        ),
    ]
