# Generated by Django 4.2.14 on 2026-05-02 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("browse_mode", "0004_browsemodepreset_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="BrowseModePickEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("built_in", "built_in"),
                            ("custom", "custom"),
                            ("apply_without_saving", "apply_without_saving"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "built_in_id",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("very_social", "very_social"),
                            ("selectively_social", "selectively_social"),
                            ("quiet", "quiet"),
                        ],
                        max_length=40,
                        null=True,
                    ),
                ),
                (
                    "preset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pick_events",
                        to="browse_mode.browsemodepreset",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="browse_mode_pick_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="browse_mode_user_id_b9c724_idx",
                    )
                ],
            },
        ),
    ]
