# Generated by Django 3.2.13 on 2024-02-24 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('content_report', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentreport',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='contentreport',
            name='content_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contentreport',
            name='object_id',
            field=models.PositiveIntegerField(default=None),
            preserve_default=False,
        ),
    ]
