# Generated by Django 4.2.11 on 2024-04-14 06:00

import adoorback.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_alter_user_friends"),
    ]

    operations = [
        migrations.AlterModelOptions(name="user", options={},),
        migrations.RemoveIndex(model_name="user", name="account_use_id_ef0f90_idx",),
        migrations.RemoveIndex(
            model_name="user", name="account_use_usernam_19aad5_idx",
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                error_messages={"unique": "A user with that username already exists."},
                help_text="Required. 20 characters or fewer. Letters (alphabet & 한글), digits and _ only.",
                max_length=20,
                validators=[adoorback.utils.validators.AdoorUsernameValidator()],
                verbose_name="username",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted__isnull", True)),
                fields=("username",),
                name="unique_active_username",
            ),
        ),
    ]
