# Generated by Django 4.2.11 on 2024-08-31 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['id']},
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['id'], name='account_use_id_ef0f90_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(condition=models.Q(('deleted__isnull', True)), fields=['username'], name='username_active_idx'),
        ),
    ]
