# Generated by Django 4.2.11 on 2024-08-25 13:29

import adoorback.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 20 characters or fewer. Letters (alphabet & 한글), digits and _ only.', max_length=20, unique=True, validators=[adoorback.utils.validators.AdoorUsernameValidator()], verbose_name='username'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['id'], name='account_use_id_ef0f90_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(condition=models.Q(('deleted__isnull', True)), fields=['username'], name='username_active_idx'),
        ),
    ]
