# Generated by Django 4.2.14 on 2024-10-30 10:48

import adoorback.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_subscription_subscription_unique_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 50 characters or fewer. Letters (alphabet & 한글), digits, -, _, and @ only.', max_length=50, validators=[adoorback.utils.validators.AdoorUsernameValidator()], verbose_name='username'),
        ),
    ]
