# Generated by Django 4.2.14 on 2024-11-02 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_user_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FriendGroup',
        ),
    ]
