# Generated by Django 4.2.14 on 2024-11-16 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_delete_friendgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='requester_choice',
            field=models.CharField(choices=[('friend', 'Friend'), ('follower', 'Follower')], max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user1_choice', models.CharField(choices=[('friend', 'Friend'), ('follower', 'Follower')], max_length=10)),
                ('user2_choice', models.CharField(choices=[('friend', 'Friend'), ('follower', 'Follower')], max_length=10)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_as_user1', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_as_user2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user1', 'user2'], name='account_con_user1_i_ce670f_idx'), models.Index(fields=['user1', 'user1_choice'], name='account_con_user1_i_8610ba_idx'), models.Index(fields=['user2', 'user2_choice'], name='account_con_user2_i_246873_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='connection',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted__isnull', True)), fields=('user1', 'user2'), name='unique_connection'),
        ),
        migrations.AddConstraint(
            model_name='connection',
            constraint=models.CheckConstraint(check=models.Q(('user1', models.F('user2')), _negated=True), name='no_self_connection'),
        ),
    ]
