# Generated by Django 3.2.13 on 2023-05-06 09:03

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_merge_20230422_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_of_signature',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='nationality',
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='signature',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
