# Generated by Django 3.2.13 on 2023-06-24 10:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20230506_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='noti_on',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='noti_time',
            field=models.TimeField(default=datetime.time(16, 0)),
        ),
    ]
