# Generated by Django 3.2.13 on 2023-06-24 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20230624_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='noti_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
