# Generated by Django 3.2.13 on 2023-09-09 05:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_user_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='noti_on',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='noti_time',
            field=models.TimeField(default=datetime.time(16, 0)),
        ),
    ]
