# Generated by Django 4.2.14 on 2024-12-08 10:47

import account.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20241116_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='noti_period_days',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), default=account.models.default_noti_period_days, help_text='Days of the week for notifications, where 0=Sunday, 1=Monday, etc.', size=None),
        ),
    ]
