# Generated by Django 4.2.14 on 2024-12-28 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_user_noti_period_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='signup_noti_status',
            field=models.JSONField(default=dict),
        ),
    ]
