# Generated by Django 4.2.14 on 2024-11-26 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_subscription_subscriber'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
