# Generated by Django 3.2.13 on 2023-10-28 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_friendgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendgroup',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
