# Generated by Django 4.2.14 on 2024-12-28 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_user_signup_noti_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='user1_choice',
            field=models.CharField(choices=[('friend', 'Friend'), ('neighbor', 'Neighbor')], max_length=10),
        ),
        migrations.AlterField(
            model_name='connection',
            name='user2_choice',
            field=models.CharField(choices=[('friend', 'Friend'), ('neighbor', 'Neighbor')], max_length=10),
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='requester_choice',
            field=models.CharField(choices=[('friend', 'Friend'), ('neighbor', 'Neighbor')], max_length=10, null=True),
        ),
    ]
