# Generated by Django 3.2.13 on 2023-10-28 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_friendgroup_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendgroup',
            name='deleted',
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='friendgroup',
            name='deleted_by_cascade',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
