# Generated by Django 4.2.14 on 2025-01-25 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_friendrequest_requestee_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_ver',
            field=models.CharField(choices=[('default', 'Default'), ('experiment', 'Experiment')], default='default', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='invited_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='user_group',
            field=models.CharField(choices=[('group_1', 'Group 1: only ver.D'), ('group_2', 'Group 2: only ver.E'), ('group_3', 'Group 3: ver.D -> ver.E'), ('group_4', 'Group 4: ver.E -> ver.D')], default='group_1', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('direct', 'Direct Participant'), ('indirect', 'Indirect Participant')], default='direct', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='ver_changed_at',
            field=models.DateTimeField(null=True),
        ),
    ]
