# Generated by Django 4.2.14 on 2025-01-28 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_friendrequest_requestee_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='friends',
        ),
        migrations.AlterField(
            model_name='connection',
            name='user1_choice',
            field=models.CharField(choices=[('friend', 'Friend'), ('close_friend', 'Close Friend')], max_length=15),
        ),
        migrations.AlterField(
            model_name='connection',
            name='user2_choice',
            field=models.CharField(choices=[('friend', 'Friend'), ('close_friend', 'Close Friend')], max_length=15),
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='requestee_choice',
            field=models.CharField(choices=[('friend', 'Friend'), ('close_friend', 'Close Friend')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='requester_choice',
            field=models.CharField(choices=[('friend', 'Friend'), ('close_friend', 'Close Friend')], max_length=15, null=True),
        ),
    ]
