# Generated by Django 3.2.13 on 2023-11-18 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_remove_user_noti_on'),
        ('account', '0014_auto_20231028_0005'),
    ]

    operations = [
    ]
