# Generated by Django 3.2.13 on 2023-11-18 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_merge_20231117_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendgroup',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
