# Generated by Django 3.2.13 on 2023-12-02 06:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_alter_friendgroup_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorite_of', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='hidden',
            field=models.ManyToManyField(blank=True, related_name='hidden_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
