# Generated by Django 4.2.14 on 2025-02-08 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_user_current_ver_user_invited_from_user_user_group_and_more'),
        ('account', '0016_connection_user1_update_past_posts_and_more'),
    ]

    operations = [
    ]
