# Generated by Django 3.2.13 on 2024-02-04 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_auto_20240119_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='pronouns',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
