# Generated by Django 4.2.14 on 2025-02-22 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_appsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsession',
            name='last_ping_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
