# Generated by Django 4.2.14 on 2025-03-01 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_rename_last_ping_time_appsession_last_touch_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='signup_noti_status',
        ),
    ]
