# Generated by Django 4.2.14 on 2025-03-08 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_remove_user_signup_noti_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_group',
            field=models.CharField(choices=[('group_1', 'Group 1: US / default (ver.R) -> experiment (ver.Q)'), ('group_2', 'Group 2: US / experiment (ver.Q) -> default (ver.R)'), ('group_3', 'Group 3: Korea / default (ver.R) -> experiment (ver.Q)'), ('group_4', 'Group 4: Korea / experiment (ver.Q) -> default (ver.R)')], default='group_1', max_length=20),
        ),
    ]
