# Generated by Django 4.2.14 on 2025-03-09 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_alter_user_user_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='requestee_update_past_posts',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='friendrequest',
            name='requester_update_past_posts',
            field=models.BooleanField(default=False),
        ),
    ]
