# Generated by Django 4.2.14 on 2025-03-15 06:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_friendrequest_requestee_update_past_posts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='persona',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('lurker', 'Lurker'), ('content_creator', 'Content Creator'), ('private_reactor', 'Private Reactor'), ('public_commenter', 'Public Commenter'), ('instant_responder', 'Instant Responder'), ('takes_my_time', 'Takes My Time'), ('daily_scroller', 'Daily Scroller'), ('occasional_checker', 'Occasional Checker'), ('scheduled_checker', 'Scheduled Checker'), ('night_owl', 'Night Owl'), ('early_bird', 'Early Bird'), ('emoji_fan', 'Emoji Fan'), ('word_person', 'Word Person'), ('poster', 'Poster'), ('commenter', 'Commenter'), ('selfie_poster', 'Selfie Poster'), ('photo_heavy', 'Photo Heavy'), ('text_poster', 'Text Poster'), ('deep_talks', 'Deep Talks'), ('curious_asker', 'Curious Asker'), ('open_book', 'Open Book'), ('closed_book', 'Closed Book'), ('nofilter_purist', '#NoFilter Purist'), ('curated_aesthetic', 'Curated Aesthetic'), ('weekend_user', 'Weekend User'), ('everyday_presence', 'Everyday Presence'), ('trend_watcher', 'Trend Watcher'), ('meme_lover', 'Meme Lover'), ('frequent_poster', 'Frequent Poster'), ('occasional_poster', 'Occasional Poster'), ('shares_many_at_once', 'Shares Many at Once'), ('random_and_casual', 'Random and Casual'), ('stream_of_consciousness', 'Stream of Consciousness'), ('one_liners', 'One Liners'), ('throwbacks', 'Throwbacks'), ('music_sharer', 'Music Sharer'), ('opinion_poster', 'Opinion Poster'), ('silent_supporter', 'Silent Supporter'), ('always_online', 'Always Online'), ('rarely_posts_but_watches_everything', 'Rarely Posts but Watches Everything'), ('binge_scroller', 'Binge Scroller'), ('silent_observer', 'Silent Observer'), ('active_listener', 'Active Listener'), ('thoughtful_responder', 'Thoughtful Responder')], max_length=50), blank=True, default=list, help_text='Multiple persona choices for the user.', size=None),
        ),
    ]
