# Generated by Django 4.2.14 on 2025-03-15 09:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_user_persona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='persona',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, help_text='Multiple persona choices for the user.', size=None),
        ),
    ]
