# Generated by Django 4.2.14 on 2025-03-16 07:27

import account.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_alter_user_persona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='persona',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), blank=True, default=account.models.default_persona, help_text='Multiple persona choices for the user.', size=None),
        ),
    ]
