# Generated by Django 4.2.14 on 2025-03-18 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0027_alter_user_persona'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_changed_pw',
            field=models.BooleanField(default=False),
        ),
    ]
