# Generated by Django 4.2.14 on 2025-03-30 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0028_user_has_changed_pw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('ko', '한국어'), ('en', '영어')], default='en', max_length=10),
        ),
    ]
