# Generated by Django 4.2.14 on 2025-04-02 04:48

import account.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0029_alter_user_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username_history',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=account.models.default_username_history, help_text='History of previously used usernames', size=None),
        ),
    ]
