# Generated by Django 4.2.14 on 2025-06-02 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0031_user_email_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='current_ver',
            field=models.CharField(choices=[('default', 'Default'), ('experiment', 'Experiment')], default='experiment', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('direct', 'Direct Participant'), ('indirect', 'Indirect Participant')], default='indirect', max_length=20),
        ),
    ]
