# Generated by Django 4.2.14 on 2026-01-11 00:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0011_alter_response_visibility'),
        ('account', '0034_persona_interest'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoverFeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('category', models.CharField(choices=[('following', 'Following'), ('mutual_friends', 'Mutual Friends'), ('mutual_traits', 'Mutual Traits'), ('anonymous', 'Anonymous'), ('random', 'Random')], max_length=20)),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discover_feed_items', to='qna.response')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discover_feeds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='account_dis_user_id_e8d940_idx')],
            },
        ),
    ]
