# Generated by Django 4.2.14 on 2026-01-11 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0035_discoverfeed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discoverfeed',
            options={'ordering': ['-created_at', 'sort_order']},
        ),
        migrations.RemoveIndex(
            model_name='discoverfeed',
            name='account_dis_user_id_e8d940_idx',
        ),
        migrations.AddField(
            model_name='discoverfeed',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='discoverfeed',
            index=models.Index(fields=['user', '-created_at', 'sort_order'], name='account_dis_user_id_04fc46_idx'),
        ),
    ]
