# Generated by Django 4.2.14 on 2026-01-29 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0011_alter_response_visibility'),
        ('note', '0009_alter_note_visibility'),
        ('account', '0036_alter_discoverfeed_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discoverfeed',
            name='note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discover_feed_items', to='note.note'),
        ),
        migrations.AlterField(
            model_name='discoverfeed',
            name='response',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discover_feed_items', to='qna.response'),
        ),
    ]
