# Generated by Django 4.2.14 on 2026-03-07 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0037_discoverfeed_note_alter_discoverfeed_response'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followrequest',
            name='requestee',
        ),
        migrations.RemoveField(
            model_name='followrequest',
            name='requester',
        ),
        migrations.AlterField(
            model_name='discoverfeed',
            name='category',
            field=models.CharField(choices=[('mutual_friends', 'Mutual Friends'), ('mutual_traits', 'Mutual Traits'), ('anonymous', 'Anonymous'), ('random', 'Random')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
        migrations.DeleteModel(
            name='FollowRequest',
        ),
    ]
