# Generated by Django 4.2.14 on 2026-03-13 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0038_remove_followrequest_requestee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio_friends_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='interests_friends_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='persona_friends_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='pronouns_friends_only',
            field=models.BooleanField(default=False),
        ),
    ]
