# Generated by Django 4.2.14 on 2026-03-20 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0039_user_bio_friends_only_user_interests_friends_only_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="interests_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="personas_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
