# Generated by Django 4.2.14 on 2026-03-20 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("check_in", "0009_update_existing_visibility"),
        ("account", "0040_add_interests_personas_updated_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscoverFeedMusic",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("mutual_friends", "Mutual Friends"),
                            ("mutual_traits", "Mutual Traits"),
                            ("anonymous", "Anonymous"),
                            ("random", "Random"),
                        ],
                        max_length=20,
                    ),
                ),
                ("sort_order", models.IntegerField(default=0)),
                (
                    "check_in",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discover_feed_music_items",
                        to="check_in.checkin",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discover_feed_music",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "sort_order"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at", "sort_order"],
                        name="account_dis_user_id_d3d908_idx",
                    )
                ],
            },
        ),
    ]
