# Generated by Django 4.2.14 on 2026-04-04 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0042_discoverfeedmusic_check_in_to_song"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomChip",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                ("text", models.CharField(max_length=25)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("music_entertainment", "Music & Entertainment"),
                            ("hobbies_activities", "Hobbies & Activities"),
                            ("on_my_mind", "On My Mind"),
                            ("as_a_friend", "As a Friend"),
                            ("online_persona", "Online Persona"),
                            ("favorite_platform", "Favorite Platform"),
                            ("least_favorite_platform", "Least Favorite Platform"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="interest",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("music_entertainment", "Music & Entertainment"),
                    ("hobbies_activities", "Hobbies & Activities"),
                    ("on_my_mind", "On My Mind"),
                    ("as_a_friend", "As a Friend"),
                    ("online_persona", "Online Persona"),
                    ("favorite_platform", "Favorite Platform"),
                    ("least_favorite_platform", "Least Favorite Platform"),
                ],
                default="hobbies_activities",
                max_length=50,
            ),
        ),
        migrations.AddIndex(
            model_name="interest",
            index=models.Index(
                fields=["category"], name="account_int_categor_b903e7_idx"
            ),
        ),
        migrations.AddField(
            model_name="customchip",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="custom_chips",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="customchip",
            index=models.Index(
                fields=["user", "category"], name="account_cus_user_id_66cb60_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="customchip",
            constraint=models.UniqueConstraint(
                fields=("user", "text", "category"), name="unique_custom_chip_per_user"
            ),
        ),
    ]
