# Generated by Django 4.2.14 on 2026-04-11 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0043_customchip_interest_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_interest_card_category',
            field=models.CharField(blank=True, choices=[('music_entertainment', 'Music & Entertainment'), ('hobbies_activities', 'Hobbies & Activities'), ('on_my_mind', 'On My Mind'), ('as_a_friend', 'As a Friend'), ('online_persona', 'Online Persona'), ('favorite_platform', 'Favorite Platform'), ('least_favorite_platform', 'Least Favorite Platform')], help_text='Last interest category shown in discover feed card, for rotation.', max_length=50, null=True),
        ),
    ]
