# Generated by Django 4.2.14 on 2026-04-11 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0044_add_last_interest_card_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='current_ver',
            field=models.CharField(choices=[('version_w', 'Version W'), ('version_q', 'Version Q')], default='version_w', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_group',
            field=models.CharField(choices=[('group_w_first', 'Start with Version W, then swap to Q'), ('group_q_first', 'Start with Version Q, then swap to W')], default='group_w_first', max_length=20),
        ),
    ]
