# Generated by Django 4.2.14 on 2026-04-25 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0047_backfill_per_category_friends_only'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='content',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='interest',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted__isnull', True)), fields=('content', 'category'), name='unique_interest_per_category'),
        ),
    ]
