# Generated by Django 4.2.14 on 2026-04-27 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0055_backfill_friend_evaluations'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='friendevaluation',
            new_name='account_fri_evaluat_a9f25b_idx',
            old_name='account_fri_evaluat_idx',
        ),
        migrations.AlterField(
            model_name='friendevaluation',
            name='deleted',
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
    ]
