# Generated by Django 4.2.14 on 2026-05-01 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0057_remove_null_subscriptions'),
    ]

    operations = [
        migrations.CreateModel(
            name='VersionSwapRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('from_version', models.CharField(choices=[('version_w', 'Version W'), ('version_q', 'Version Q')], max_length=20)),
                ('to_version', models.CharField(choices=[('version_w', 'Version W'), ('version_q', 'Version Q')], max_length=20)),
                ('reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='version_swap_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='account_ver_created_2c4819_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='versionswaprequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending'), ('deleted__isnull', True)), fields=('user',), name='unique_pending_version_swap_request'),
        ),
    ]
