# Generated by Django 4.2.14 on 2026-05-01 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0059_rename_versionswaprequest_to_versionswitchrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='as_a_friend_visibility',
            field=models.CharField(choices=[('public', 'Public'), ('friends', 'Friends'), ('close_friends', 'Close Friends'), ('only_me', 'Only Me')], default='public', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='bio_visibility',
            field=models.CharField(choices=[('public', 'Public'), ('friends', 'Friends'), ('close_friends', 'Close Friends'), ('only_me', 'Only Me')], default='public', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='favorite_platform_visibility',
            field=models.CharField(choices=[('public', 'Public'), ('friends', 'Friends'), ('close_friends', 'Close Friends'), ('only_me', 'Only Me')], default='public', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='hobbies_activities_visibility',
            field=models.CharField(choices=[('public', 'Public'), ('friends', 'Friends'), ('close_friends', 'Close Friends'), ('only_me', 'Only Me')], default='public', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='least_favorite_platform_visibility',
            field=models.CharField(choices=[('public', 'Public'), ('friends', 'Friends'), ('close_friends', 'Close Friends'), ('only_me', 'Only Me')], default='public', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='music_entertainment_visibility',
            field=models.CharField(choices=[('public', 'Public'), ('friends', 'Friends'), ('close_friends', 'Close Friends'), ('only_me', 'Only Me')], default='public', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='name_visibility',
            field=models.CharField(choices=[('public', 'Public'), ('friends', 'Friends'), ('close_friends', 'Close Friends'), ('only_me', 'Only Me')], default='public', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='on_my_mind_visibility',
            field=models.CharField(choices=[('public', 'Public'), ('friends', 'Friends'), ('close_friends', 'Close Friends'), ('only_me', 'Only Me')], default='public', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='online_persona_visibility',
            field=models.CharField(choices=[('public', 'Public'), ('friends', 'Friends'), ('close_friends', 'Close Friends'), ('only_me', 'Only Me')], default='public', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='pronouns_visibility',
            field=models.CharField(choices=[('public', 'Public'), ('friends', 'Friends'), ('close_friends', 'Close Friends'), ('only_me', 'Only Me')], default='public', max_length=20),
        ),
    ]
