# Generated by Django 4.2.14 on 2026-05-01 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0061_backfill_visibility_from_friends_only'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='as_a_friend_friends_only',
        ),
        migrations.RemoveField(
            model_name='user',
            name='bio_friends_only',
        ),
        migrations.RemoveField(
            model_name='user',
            name='favorite_platform_friends_only',
        ),
        migrations.RemoveField(
            model_name='user',
            name='hobbies_activities_friends_only',
        ),
        migrations.RemoveField(
            model_name='user',
            name='interests_friends_only',
        ),
        migrations.RemoveField(
            model_name='user',
            name='least_favorite_platform_friends_only',
        ),
        migrations.RemoveField(
            model_name='user',
            name='music_entertainment_friends_only',
        ),
        migrations.RemoveField(
            model_name='user',
            name='on_my_mind_friends_only',
        ),
        migrations.RemoveField(
            model_name='user',
            name='online_persona_friends_only',
        ),
        migrations.RemoveField(
            model_name='user',
            name='persona_friends_only',
        ),
        migrations.RemoveField(
            model_name='user',
            name='pronouns_friends_only',
        ),
    ]
