# Generated by Django 4.2.14 on 2026-05-01 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0063_user_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="basic_identities_visibility",
            field=models.CharField(
                choices=[
                    ("public", "Public"),
                    ("friends", "Friends"),
                    ("close_friends", "Close Friends"),
                    ("only_me", "Only Me"),
                ],
                default="public",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="values_allyship_visibility",
            field=models.CharField(
                choices=[
                    ("public", "Public"),
                    ("friends", "Friends"),
                    ("close_friends", "Close Friends"),
                    ("only_me", "Only Me"),
                ],
                default="public",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="customchip",
            name="category",
            field=models.CharField(
                choices=[
                    ("music_entertainment", "Music & Entertainment"),
                    ("hobbies_activities", "Hobbies & Activities"),
                    ("on_my_mind", "On My Mind"),
                    ("as_a_friend", "As a Friend"),
                    ("online_persona", "Online Persona"),
                    ("favorite_platform", "Favorite Platform"),
                    ("least_favorite_platform", "Least Favorite Platform"),
                    ("basic_identities", "Basic Identities"),
                    ("values_allyship", "Values & Allyship"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="interest",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("music_entertainment", "Music & Entertainment"),
                    ("hobbies_activities", "Hobbies & Activities"),
                    ("on_my_mind", "On My Mind"),
                    ("as_a_friend", "As a Friend"),
                    ("online_persona", "Online Persona"),
                    ("favorite_platform", "Favorite Platform"),
                    ("least_favorite_platform", "Least Favorite Platform"),
                    ("basic_identities", "Basic Identities"),
                    ("values_allyship", "Values & Allyship"),
                ],
                default="hobbies_activities",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_interest_card_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("music_entertainment", "Music & Entertainment"),
                    ("hobbies_activities", "Hobbies & Activities"),
                    ("on_my_mind", "On My Mind"),
                    ("as_a_friend", "As a Friend"),
                    ("online_persona", "Online Persona"),
                    ("favorite_platform", "Favorite Platform"),
                    ("least_favorite_platform", "Least Favorite Platform"),
                    ("basic_identities", "Basic Identities"),
                    ("values_allyship", "Values & Allyship"),
                ],
                help_text="Last interest category shown in discover feed card, for rotation.",
                max_length=50,
                null=True,
            ),
        ),
    ]
