# Generated by Django 4.2.14 on 2026-05-02 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0065_reorder_chip_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_received_first_archive_noti',
            field=models.BooleanField(default=False),
        ),
    ]
