# Generated by Django 4.2.14 on 2026-05-02 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0066_add_first_archive_noti_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendevaluation',
            name='relationship_type',
            field=models.CharField(blank=True, choices=[('school_friend', 'School Friend'), ('coworker', 'Coworker'), ('family', 'Family'), ('online_friend', 'Online Friend'), ('club_community', 'Club/Community'), ('not_yet', 'Not Yet Met'), ('other', 'Other')], max_length=20, null=True),
        ),
    ]
