# Generated by Django 4.2.14 on 2026-05-02 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0067_alter_friendevaluation_relationship_type'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='customchip',
            name='unique_custom_chip_per_user',
        ),
        migrations.AddConstraint(
            model_name='customchip',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted__isnull', True)), fields=('user', 'text', 'category'), name='unique_custom_chip_per_user'),
        ),
    ]
