# Generated by Django 4.2.14 on 2026-05-03 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0068_fix_custom_chip_unique_constraint_soft_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discoverfeed',
            name='category',
            field=models.CharField(choices=[('mutual_friends', 'Mutual Friends'), ('mutual_traits', 'Mutual Traits'), ('anonymous', 'Anonymous'), ('random', 'Random'), ('yesterday_mission', 'Yesterday Mission'), ('yesterday_question', 'Yesterday Question'), ('yesterday_post', 'Yesterday Post'), ('recommended', 'Recommended Post')], max_length=20),
        ),
        migrations.AlterField(
            model_name='discoverfeedmusic',
            name='category',
            field=models.CharField(choices=[('mutual_friends', 'Mutual Friends'), ('mutual_traits', 'Mutual Traits'), ('anonymous', 'Anonymous'), ('random', 'Random'), ('yesterday_mission', 'Yesterday Mission'), ('yesterday_question', 'Yesterday Question'), ('yesterday_post', 'Yesterday Post'), ('recommended', 'Recommended Post')], max_length=20),
        ),
    ]
