# Generated by Django 4.2.14 on 2026-07-07 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0070_user_invite_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="daily_prompt_push_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Whether this user receives daily prompt push reminders.",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="push_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Whether this user receives any push notifications.",
            ),
        ),
    ]
