# Generated by Django 4.2.14 on 2024-11-26 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='subscription',
            name='category_su_sharing_ac1f89_idx',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='sharing_scope',
        ),
    ]
