# Generated by Django 4.2.14 on 2024-12-14 20:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('category', '0002_remove_subscription_category_su_sharing_ac1f89_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_categories', to=settings.AUTH_USER_MODEL),
        ),
    ]
