# Generated by Django 4.2.14 on 2024-12-14 20:34

from django.db import migrations

def set_default_owners(apps, schema_editor):
    Category = apps.get_model('category', 'Category')
    User = apps.get_model('account', 'User')
    
    # Get the first admin user as default owner
    default_owner = User.objects.filter(is_superuser=True).first()
    if not default_owner:
        default_owner = User.objects.first()
    
    if default_owner:
        Category.objects.filter(owner__isnull=True).update(owner=default_owner)

class Migration(migrations.Migration):
    dependencies = [
        ('category', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(set_default_owners, reverse_code=migrations.RunPython.noop),
    ]
