# Generated by Django 4.2.14 on 2024-12-14 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_category_owner'),
        ('category', '0004_set_category_owners'),
    ]

    operations = [
    ]
