# Generated by Django 3.2.13 on 2023-11-18 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reaction', '0002_auto_20231110_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='emoji',
            field=models.CharField(max_length=20),
        ),
    ]
