# Generated by Django 4.2.14 on 2026-04-27 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reaction', '0002_add_component_to_reaction'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reaction',
            name='unique_reaction_no_component',
        ),
        migrations.RemoveConstraint(
            model_name='reaction',
            name='unique_reaction_with_component',
        ),
        migrations.AddConstraint(
            model_name='reaction',
            constraint=models.UniqueConstraint(condition=models.Q(('component__isnull', True), ('deleted__isnull', True)), fields=('user', 'emoji', 'content_type', 'object_id'), name='unique_reaction_no_component'),
        ),
        migrations.AddConstraint(
            model_name='reaction',
            constraint=models.UniqueConstraint(condition=models.Q(('component__isnull', False), ('deleted__isnull', True)), fields=('user', 'emoji', 'content_type', 'object_id', 'component'), name='unique_reaction_with_component'),
        ),
    ]
