# Generated by Django 4.2.14 on 2025-01-17 06:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.IntegerField()),
                ('offset', models.IntegerField(default=-1)),
                ('length', models.IntegerField(default=0)),
                ('username_str', models.CharField(default='', max_length=20)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('tagged_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_set', to=settings.AUTH_USER_MODEL)),
                ('tagging_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagging_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='usertag',
            constraint=models.UniqueConstraint(fields=('tagging_user', 'tagged_user', 'content_type', 'object_id', 'offset'), name='unique_user_tag'),
        ),
    ]
