# Generated by Django 4.2.14 on 2025-01-17 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TranslateResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translatedText', models.TextField(blank=True)),
                ('detectedSourceLanguage', models.TextField()),
            ],
        ),
    ]
