# Generated by Django 4.2.14 on 2024-11-16 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='translateresponse',
            old_name='translated_text',
            new_name='translatedText',
        ),
    ]
