# Generated by Django 3.2.18 on 2023-05-12 00:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import moment.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Moment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(validators=[django.core.validators.MinLengthValidator(1, 'content length must be greater than 1')])),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('date', models.CharField(max_length=20)),
                ('mood', models.CharField(blank=True, max_length=20, null=True)),
                ('photo', models.ImageField(blank=True, null=True, storage=moment.models.OverwriteStorage(), upload_to=moment.models.to_profile_images)),
                ('description', models.CharField(blank=True, max_length=20, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moment_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='moment',
            index=models.Index(fields=['-id'], name='moment_mome_id_d03a9d_idx'),
        ),
    ]
