# Generated by Django 3.2.18 on 2023-05-12 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moment',
            name='content',
        ),
    ]
