# Generated by Django 3.2.18 on 2023-05-20 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moment', '0002_remove_moment_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moment',
            name='date',
            field=models.CharField(max_length=8),
        ),
    ]
