# Generated by Django 3.2.13 on 2023-09-03 04:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('moment', '0006_auto_20230814_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='moment',
            name='readers',
            field=models.ManyToManyField(related_name='read_moments', to=settings.AUTH_USER_MODEL),
        ),
    ]
