# Generated by Django 3.2.13 on 2024-02-09 07:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('is_active', models.BooleanField(default=False)),
                ('mood', models.CharField(blank=True, max_length=5, null=True)),
                ('availability', models.CharField(choices=[('available', 'Available'), ('busy', 'Busy'), ('might_get_distracted', 'Might get distracted'), ('urgent_only', 'Urgent only'), ('about_to_sleep', 'About to sleep'), ('studying', 'Studying'), ('in_transit', 'In transit'), ('feeling_social', 'Feeling social'), ('feeling_quiet', 'Feeling quiet')], default='no_status', max_length=20)),
                ('description', models.CharField(blank=True, max_length=88, null=True)),
                ('track_id', models.CharField(blank=True, max_length=50, null=True)),
                ('share_everyone', models.BooleanField(default=True)),
                ('readers', models.ManyToManyField(related_name='read_check_ins', to=settings.AUTH_USER_MODEL)),
                ('share_friends', models.ManyToManyField(blank=True, related_name='shared_check_ins', to=settings.AUTH_USER_MODEL)),
                ('share_groups', models.ManyToManyField(blank=True, related_name='shared_check_ins', to='account.FriendGroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_in_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='checkin',
            index=models.Index(fields=['is_active'], name='check_in_ch_is_acti_2283ae_idx'),
        ),
    ]
