# Generated by Django 3.2.13 on 2023-11-18 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_in', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='checkin',
            index=models.Index(fields=['is_active'], name='check_in_ch_is_acti_2283ae_idx'),
        ),
    ]
