# Generated by Django 4.2.11 on 2024-06-01 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_in', '0003_remove_checkin_share_everyone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='availability',
            field=models.CharField(blank=True, choices=[('available', 'Available'), ('busy', 'Busy'), ('might_get_distracted', 'Might get distracted'), ('urgent_only', 'Urgent only'), ('about_to_sleep', 'About to sleep'), ('studying', 'Studying'), ('in_transit', 'In transit'), ('feeling_social', 'Feeling social'), ('feeling_quiet', 'Feeling quiet')], max_length=20, null=True),
        ),
    ]
