# Generated by Django 3.2.13 on 2023-11-18 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_in', '0003_alter_checkin_mood'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='track_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
