# Generated by Django 4.2.14 on 2025-03-15 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_in', '0004_alter_checkin_availability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkin',
            name='availability',
        ),
        migrations.AddField(
            model_name='checkin',
            name='social_battery',
            field=models.CharField(blank=True, choices=[('completely_drained', 'Completely Drained'), ('low', 'Low Social Battery'), ('needs_recharge', 'Needs Recharge'), ('moderate', 'Moderate'), ('fully_charged', 'Fully Charged'), ('super_social', 'Super Social Mode (HMU!)')], max_length=30, null=True),
        ),
    ]
