# Generated by Django 3.2.13 on 2024-02-04 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_in', '0004_checkin_track_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='availability',
            field=models.CharField(choices=[('available', 'Available'), ('busy', 'Busy'), ('might_get_distracted', 'Might get distracted'), ('urgent_only', 'Urgent only'), ('about_to_sleep', 'About to sleep'), ('studying', 'Studying'), ('in_transit', 'In transit'), ('feeling_social', 'Feeling social'), ('feeling_quiet', 'Feeling quiet')], default='no_status', max_length=20),
        ),
    ]
