# Generated by Django 4.2.14 on 2026-01-29 00:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_in', '0006_alter_checkin_social_battery'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='visibility',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, default=list, size=None),
        ),
    ]
