# Generated by Django 4.2.14 on 2026-02-23 03:21

import check_in.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_in', '0007_checkin_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='visibility',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, default=check_in.models.list_public, size=None),
        ),
    ]
