# Generated by Django 4.2.14 on 2026-03-27 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_in', '0010_create_song_remove_checkin_track_id'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='song',
            new_name='check_in_so_is_acti_55abb2_idx',
            old_name='check_in_so_is_acti_idx',
        ),
        migrations.AlterField(
            model_name='song',
            name='deleted',
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
