# Generated by Django 4.2.14 on 2026-04-04 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "check_in",
            "0011_rename_check_in_so_is_acti_idx_check_in_so_is_acti_55abb2_idx_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Poke",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "component_type",
                    models.CharField(
                        choices=[
                            ("song", "Song"),
                            ("status", "Status"),
                            ("battery", "Battery"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_pokes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_pokes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["sender", "created_at"],
                        name="check_in_po_sender__c2c3f6_idx",
                    ),
                    models.Index(
                        fields=["receiver"], name="check_in_po_receive_1c831f_idx"
                    ),
                ],
            },
        ),
    ]
