# Generated by Django 4.2.14 on 2026-04-05 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("check_in", "0012_poke"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkin",
            name="battery_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="checkin",
            name="battery_visibility",
            field=models.CharField(
                choices=[
                    ("public", "Public"),
                    ("friends", "Friends"),
                    ("close_friends", "Close Friends"),
                    ("only_me", "Only Me"),
                ],
                default="friends",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="checkin",
            name="mood_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="checkin",
            name="mood_visibility",
            field=models.CharField(
                choices=[
                    ("public", "Public"),
                    ("friends", "Friends"),
                    ("close_friends", "Close Friends"),
                    ("only_me", "Only Me"),
                ],
                default="friends",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="checkin",
            name="song_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="checkin",
            name="song_visibility",
            field=models.CharField(
                choices=[
                    ("public", "Public"),
                    ("friends", "Friends"),
                    ("close_friends", "Close Friends"),
                    ("only_me", "Only Me"),
                ],
                default="public",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="checkin",
            name="thought_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="checkin",
            name="thought_visibility",
            field=models.CharField(
                choices=[
                    ("public", "Public"),
                    ("friends", "Friends"),
                    ("close_friends", "Close Friends"),
                    ("only_me", "Only Me"),
                ],
                default="friends",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="poke",
            name="component_type",
            field=models.CharField(
                choices=[
                    ("song", "Song"),
                    ("mood", "Mood"),
                    ("thought", "Thought Snippet"),
                    ("battery", "Battery"),
                ],
                max_length=20,
            ),
        ),
    ]
