# Generated by Django 4.2.14 on 2026-04-11 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("check_in", "0013_checkin_battery_updated_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="checkin",
            old_name="description",
            new_name="thought",
        ),
        # Widen the varchar column so JSON array strings fit, then convert data,
        # then change to JSONField.
        migrations.RunSQL(
            sql="ALTER TABLE check_in_checkin ALTER COLUMN mood TYPE text;",
            reverse_sql="ALTER TABLE check_in_checkin ALTER COLUMN mood TYPE varchar(5);",
        ),
        migrations.RunSQL(
            sql=[
                # Convert non-null, non-empty mood values to JSON arrays
                (
                    "UPDATE check_in_checkin SET mood = '[\"' || mood || '\"]' "
                    "WHERE mood IS NOT NULL AND mood != '';"
                ),
                # Convert empty/null to empty arrays
                "UPDATE check_in_checkin SET mood = '[]' WHERE mood IS NULL OR mood = '';",
            ],
            reverse_sql=[
                # Reverse: extract first element from JSON array
                (
                    "UPDATE check_in_checkin SET mood = mood::jsonb->>0 "
                    "WHERE mood IS NOT NULL AND mood != '[]';"
                ),
                "UPDATE check_in_checkin SET mood = NULL WHERE mood = '[]';",
            ],
        ),
        migrations.AlterField(
            model_name="checkin",
            name="mood",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
