# Generated by Django 4.2.14 on 2026-04-20 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_in', '0014_rename_description_to_thought_and_mood_to_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='thought',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
