# Generated by Django 4.2.14 on 2026-04-24 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("check_in", "0015_alter_checkin_thought"),
    ]

    operations = [
        migrations.CreateModel(
            name="CheckInComponentEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "component",
                    models.CharField(
                        choices=[
                            ("battery", "Battery"),
                            ("mood", "Mood"),
                            ("thought", "Thought"),
                            ("song", "Song"),
                        ],
                        max_length=20,
                    ),
                ),
                ("data", models.JSONField(blank=True, default=dict)),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("friends", "Friends"),
                            ("close_friends", "Close Friends"),
                            ("only_me", "Only Me"),
                        ],
                        default="friends",
                        max_length=20,
                    ),
                ),
                ("superseded_at", models.DateTimeField(blank=True, null=True)),
                ("is_pinned", models.BooleanField(default=False)),
                (
                    "pin_visibility",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("public", "Public"),
                            ("friends", "Friends"),
                            ("close_friends", "Close Friends"),
                            ("only_me", "Only Me"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="check_in_entry_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["owner", "component", "-created_at"],
                        name="check_in_ch_owner_i_a2c41b_idx",
                    ),
                    models.Index(
                        fields=["owner", "is_pinned"],
                        name="check_in_ch_owner_i_6e59fa_idx",
                    ),
                    models.Index(
                        fields=["owner", "component", "superseded_at"],
                        name="check_in_ch_owner_i_2b9634_idx",
                    ),
                ],
            },
        ),
    ]
