# Generated by Django 4.2.14 on 2026-04-25 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_in', '0018_checkinpost'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='checkinpost',
            new_name='check_in_ch_created_e47cad_idx',
            old_name='check_in_ch_created_idx',
        ),
        migrations.RenameIndex(
            model_name='checkinpost',
            new_name='check_in_ch_author__f8f1ae_idx',
            old_name='check_in_ch_author_created_idx',
        ),
        migrations.AlterField(
            model_name='checkinpost',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
