# Generated by Django 4.2.14 on 2026-05-01 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_in', '0022_checkinpost_video_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkinpost',
            name='pin_visibility',
            field=models.CharField(blank=True, choices=[('public', 'Public'), ('friends', 'Friends'), ('close_friends', 'Close Friends')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='checkinpost',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('friends', 'Friends'), ('close_friends', 'Close Friends')], default='friends', max_length=20),
        ),
    ]
