# Generated by Django 4.2.14 on 2026-05-03 23:29

from django.db import migrations, models


def backfill_responded_at(apps, schema_editor):
    Poke = apps.get_model('check_in', 'Poke')
    Poke.objects.filter(responded_at__isnull=True).update(responded_at=models.F('created_at'))


class Migration(migrations.Migration):

    dependencies = [
        ('check_in', '0023_add_public_to_check_in_post_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='poke',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_responded_at, migrations.RunPython.noop),
    ]
