# Generated by Django 4.2.14 on 2026-05-04 00:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('check_in', '0024_poke_responded_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateAcknowledgment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_acknowledgments', to='check_in.checkincomponententry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_acknowledgments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='privateacknowledgment',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted__isnull', True)), fields=('user', 'entry'), name='unique_private_ack_per_user_entry'),
        ),
    ]
