# Generated by Django 4.2.14 on 2026-05-04 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("check_in", "0025_add_private_acknowledgment"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkin",
            name="battery_archive_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="checkin",
            name="mood_archive_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="checkin",
            name="song_archive_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="checkin",
            name="thought_archive_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
