# Generated by Django 4.2.14 on 2026-05-10 03:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "check_in",
            "0026_checkin_battery_archive_at_checkin_mood_archive_at_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="CheckInRead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("read_at", models.DateTimeField(auto_now=True)),
                (
                    "check_in",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="read_records",
                        to="check_in.checkin",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="check_in_read_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "check_in"],
                        name="check_in_ch_user_id_8489c2_idx",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="checkinread",
            constraint=models.UniqueConstraint(
                fields=("check_in", "user"), name="unique_check_in_read"
            ),
        ),
        migrations.RunPython(
            code=lambda apps, _: _backfill_check_in_read(apps),
            reverse_code=migrations.RunPython.noop,
        ),
    ]


def _backfill_check_in_read(apps):
    """Seed CheckInRead from the existing CheckIn.readers M2M.

    Existing readers don't have a recorded read_at — we only know they
    read it at *some* point. Conservative choice: set read_at to the
    check-in's `updated_at`, treating them as "having read up through
    the latest version." That makes any FUTURE component edit show up
    as unread (correct), while any change BEFORE the migration is
    treated as already seen (acceptable, since users had no per-component
    feedback before this anyway).
    """
    CheckIn = apps.get_model("check_in", "CheckIn")
    CheckInRead = apps.get_model("check_in", "CheckInRead")
    Through = CheckIn.readers.through

    rows = []
    # `update_at` exists on AdoorTimestampedModel; for any older check-in
    # rows that somehow lack it, fall back to created_at via COALESCE in SQL.
    for through_row in Through.objects.select_related("checkin").iterator():
        ci = through_row.checkin
        read_at = ci.updated_at or ci.created_at
        rows.append(
            CheckInRead(
                check_in_id=through_row.checkin_id,
                user_id=through_row.user_id,
                # auto_now fires on save() — bulk_create sidesteps that, so
                # rely on the model's pre_save default. We override directly
                # by setting the field after construction:
            )
        )
        rows[-1].read_at = read_at

    if rows:
        CheckInRead.objects.bulk_create(rows, ignore_conflicts=True, batch_size=1000)
