# Generated by Django 4.2.14 on 2026-02-19 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pin', '0002_pin_deleted_pin_deleted_by_cascade'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pin',
            name='unique_pin',
        ),
        migrations.AddConstraint(
            model_name='pin',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted__isnull', True)), fields=('user', 'content_type', 'object_id'), name='unique_pin'),
        ),
    ]
