# Generated by Django 3.2.13 on 2024-02-12 06:33

from django.conf import settings
from django.db import migrations, models
import note.models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='share_everyone',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='note',
            name='share_friends',
            field=models.ManyToManyField(blank=True, related_name='shared_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='note',
            name='share_groups',
            field=models.ManyToManyField(blank=True, related_name='shared_notes', to='account.FriendGroup'),
        ),
        migrations.AlterField(
            model_name='note',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=note.models.OverwriteStorage(), upload_to=note.models.note_image_path),
        ),
    ]
