# Generated by Django 4.2.11 on 2024-04-05 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("note", "0004_auto_20240316_0927"),
    ]

    operations = [
        migrations.RemoveField(model_name="note", name="share_everyone",),
        migrations.RemoveField(model_name="note", name="share_friends",),
        migrations.RemoveField(model_name="note", name="share_groups",),
    ]
