# Generated by Django 4.2.11 on 2024-05-04 05:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('note', '0005_remove_note_share_everyone_remove_note_share_friends_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='readers',
            field=models.ManyToManyField(related_name='read_notes', to=settings.AUTH_USER_MODEL),
        ),
    ]
