# Generated by Django 4.2.15 on 2024-08-24 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0006_note_readers'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
    ]
