# Generated by Django 4.2.14 on 2025-12-26 07:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0008_note_visibility'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='note',
                    name='visibility',
                    field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, default=list, size=None),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql='ALTER TABLE note_note ALTER COLUMN visibility TYPE varchar(20)[] USING ARRAY[visibility]::varchar(20)[];',
                    reverse_sql='ALTER TABLE note_note ALTER COLUMN visibility TYPE varchar(20) USING visibility[1];',
                ),
            ],
        ),
    ]
