# Generated by Django 4.2.14 on 2026-05-02 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("note", "0012_notevideo_deleted_by_cascade_alter_notevideo_deleted_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="mission_attempt_number",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="note",
            name="mission_prompt",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="note",
            name="share_type",
            field=models.CharField(
                choices=[
                    ("regular", "Regular"),
                    ("tmi_of_the_day", "TMI of the Day"),
                    ("photo_of_the_day", "Photo of the Day"),
                    ("mission", "Mission"),
                ],
                default="regular",
                max_length=20,
            ),
        ),
    ]
