# Generated by Django 4.2.14 on 2026-05-08 22:46

from django.db import migrations, models


def backfill_mission_ids(apps, schema_editor):
    Note = apps.get_model('note', 'Note')
    Mission = apps.get_model('adoorback', 'Mission')
    for note in Note.objects.filter(share_type='mission', mission_id__isnull=True):
        mission = Mission.objects.filter(prompt=note.mission_prompt).first()
        if mission:
            note.mission_id = mission.id
            note.save(update_fields=['mission_id'])


def reverse_backfill(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0013_note_mission_attempt_number_note_mission_prompt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='mission_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_mission_ids, reverse_backfill),
    ]
