# Generated by Django 4.2.14 on 2026-01-29 02:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('check_in', '0007_checkin_visibility'),
        ('playlist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='song',
            name='deleted_by_cascade',
        ),
        migrations.RemoveField(
            model_name='song',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='song',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PlaylistFeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('check_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='check_in.checkin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_feed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'created_at'], name='playlist_pl_user_id_ae0547_idx')],
            },
        ),
    ]
