# Generated by Django 4.2.14 on 2026-01-29 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0002_remove_song_deleted_remove_song_deleted_by_cascade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlistfeed',
            name='feed_id',
            field=models.UUIDField(null=True),
        ),
    ]
