# Generated by Django 4.2.14 on 2024-11-23 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PingRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ping_rooms_as_user1', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ping_rooms_as_user2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('emoji', models.CharField(blank=True, choices=[('wave', '👋'), ('smile', '😊'), ('heart', '❤️'), ('cry', '😭'), ('laugh', '🤣')], max_length=20, null=True)),
                ('content', models.TextField(blank=True)),
                ('is_read', models.BooleanField(default=False)),
                ('ping_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pings', to='ping.pingroom')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_pings', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_pings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='pingroom',
            index=models.Index(fields=['user1', 'user2'], name='ping_pingro_user1_i_212f4e_idx'),
        ),
        migrations.AddConstraint(
            model_name='pingroom',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted__isnull', True)), fields=('user1', 'user2'), name='unique_ping_room'),
        ),
        migrations.AddConstraint(
            model_name='pingroom',
            constraint=models.CheckConstraint(check=models.Q(('user1', models.F('user2')), _negated=True), name='no_self_ping_room'),
        ),
        migrations.AddIndex(
            model_name='ping',
            index=models.Index(fields=['ping_room', 'created_at'], name='ping_ping_ping_ro_fb0e3b_idx'),
        ),
        migrations.AddIndex(
            model_name='ping',
            index=models.Index(fields=['receiver', 'is_read'], name='ping_ping_receive_4e879a_idx'),
        ),
    ]
