# Generated by Django 4.2.14 on 2025-03-01 05:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ping',
            name='content',
            field=models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(10000)]),
        ),
    ]
