# Generated by Django 4.2.11 on 2024-08-17 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fcm_django', '0011_remove_fcmdevice_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomFCMDevice',
            fields=[
                ('fcmdevice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fcm_django.fcmdevice')),
                ('language', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'FCM device',
                'abstract': False,
            },
            bases=('fcm_django.fcmdevice',),
        ),
    ]
