# Generated by Django 4.2.11 on 2024-07-27 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_fcm', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomFCMDevice',
        ),
    ]
