# Generated by Django 4.2.11 on 2024-07-27 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_fcm', '0002_delete_customfcmdevice'),
    ]

    operations = [
    ]
