# Generated by Django 3.2.13 on 2024-02-12 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='available_limit',
        ),
        migrations.RemoveField(
            model_name='response',
            name='date',
        ),
        migrations.RemoveField(
            model_name='response',
            name='share_with_friends',
        ),
    ]
