# Generated by Django 3.2.13 on 2024-02-12 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0002_auto_20240211_2233'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='responserequest',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
