# Generated by Django 4.2.11 on 2024-04-05 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qna", "0004_alter_response_share_everyone"),
    ]

    operations = [
        migrations.RemoveField(model_name="response", name="share_everyone",),
        migrations.RemoveField(model_name="response", name="share_friends",),
        migrations.RemoveField(model_name="response", name="share_groups",),
    ]
