# Generated by Django 4.2.11 on 2024-05-04 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0005_remove_response_share_everyone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='selected_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
