# Generated by Django 4.2.15 on 2024-08-24 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0006_alter_question_selected_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
    ]
