# Generated by Django 4.2.14 on 2025-02-02 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0008_response_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='visibility',
            field=models.CharField(choices=[('friends', 'Friends'), ('close_friends', 'Close Friends')], default='close_friends', max_length=20),
        ),
    ]
