# Generated by Django 4.2.14 on 2025-12-26 06:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0010_alter_response_visibility'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='ALTER TABLE "qna_response" ALTER COLUMN "visibility" TYPE varchar(20)[] USING ARRAY["visibility"]::varchar(20)[];',
                    reverse_sql='ALTER TABLE "qna_response" ALTER COLUMN "visibility" TYPE varchar(20) USING "visibility"[1];',
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='response',
                    name='visibility',
                    field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, default=list, size=None),
                ),
            ],
        ),
    ]
