# Generated by Django 3.2.13 on 2023-05-14 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_auto_20230318_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='is_admin_question',
            field=models.BooleanField(default=True),
        ),
    ]
