# Generated by Django 3.2.13 on 2023-06-06 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_auto_20230603_1817'),
        ('feed', '0006_auto_20230527_0834'),
    ]

    operations = [
    ]
