# Generated by Django 3.2.13 on 2023-06-03 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0006_auto_20230527_0834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multiresponse',
            name='author',
        ),
        migrations.RemoveField(
            model_name='multiresponse',
            name='choices',
        ),
        migrations.RemoveField(
            model_name='multiresponse',
            name='multi_question',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='MultiQuestion',
        ),
        migrations.DeleteModel(
            name='MultiResponse',
        ),
    ]
