# Generated by Django 3.2.13 on 2023-05-27 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0007_auto_20230527_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiquestion',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multi_question_set', to='feed.topic'),
        ),
    ]
