# Generated by Django 3.2.13 on 2023-07-08 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0007_auto_20230603_1638'),
        ('feed', '0007_merge_0005_auto_20230603_1817_0006_auto_20230527_0834'),
    ]

    operations = [
    ]