# Generated by Django 3.2.13 on 2023-07-15 08:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0008_merge_20230708_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='content_en',
            field=models.TextField(null=True, validators=[django.core.validators.MinLengthValidator(1, 'content length must be greater than 1')]),
        ),
        migrations.AddField(
            model_name='question',
            name='content_ko',
            field=models.TextField(null=True, validators=[django.core.validators.MinLengthValidator(1, 'content length must be greater than 1')]),
        ),
    ]
