# Generated by Django 3.2.13 on 2023-08-15 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0009_auto_20230715_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='date',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
