# Generated by Django 3.2.13 on 2023-08-15 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0010_response_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='available_limit',
            field=models.DateTimeField(default='2008-10-03'),
        ),
        migrations.AlterField(
            model_name='response',
            name='date',
            field=models.DateField(default='2008-10-03'),
        ),
    ]
