# Generated by Django 3.2.13 on 2023-09-03 04:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feed', '0011_auto_20230814_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='readers',
            field=models.ManyToManyField(related_name='read_responses', to=settings.AUTH_USER_MODEL),
        ),
    ]
