# Generated by Django 3.2.13 on 2023-10-22 08:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0012_friendgroup'),
        ('feed', '0012_response_readers'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='share_friends',
            field=models.ManyToManyField(related_name='shared_responses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='response',
            name='share_groups',
            field=models.ManyToManyField(related_name='shared_responses', to='account.FriendGroup'),
        ),
    ]
