# Generated by Django 3.2.13 on 2023-10-28 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0013_auto_20231022_0143'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='share_everyone',
            field=models.BooleanField(default=True),
        ),
    ]
