# Generated by Django 3.2.13 on 2023-10-28 07:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0014_auto_20231028_0005'),
        ('feed', '0014_response_share_everyone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='share_friends',
            field=models.ManyToManyField(blank=True, related_name='shared_responses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='response',
            name='share_groups',
            field=models.ManyToManyField(blank=True, related_name='shared_responses', to='account.FriendGroup'),
        ),
    ]
