# Generated by Django 3.2.13 on 2024-01-13 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0015_auto_20231028_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='available_limit',
            field=models.DateTimeField(default='3000-10-03'),
        ),
    ]
