# Generated by Django 4.2.14 on 2026-04-11 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("chat", "0002_cleanup_old_apps"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="shared_content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="shared_object_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
