# Generated by Django 4.2.11 on 2024-04-13 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20240323_0026'),
        ('chat', '0003_message_parent'),
    ]

    operations = [
    ]
