# Generated by Django 4.2.14 on 2026-04-25 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0009_ensure_all_tables_and_columns"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatroom",
            name="is_wit_admin_blast_room",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="chatroom",
            name="is_wit_admin_proxy",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="is_wit_admin_mirror",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
