# Generated by Django 4.2.14 on 2026-04-25 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0011_wit_admin_flags_backfill"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatroom",
            name="is_wit_admin_blast_room",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="chatroom",
            name="is_wit_admin_proxy",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="message",
            name="is_wit_admin_mirror",
            field=models.BooleanField(default=False),
        ),
    ]
