# Generated by Django 4.2.14 on 2026-05-01 02:16

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_witbotconversationstate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=account.models.OverwriteStorage(), upload_to='chat_images/'),
        ),
    ]
