# Generated by Django 4.2.14 on 2026-05-01 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0015_alter_message_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="bot_payload",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
