# Generated by Django 4.2.14 on 2026-05-04 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0017_onboardingscreenshot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="event_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Message"),
                    ("member_added", "Member Added"),
                    ("member_left", "Member Left"),
                    ("wit_welcome_card", "wit_bot welcome card"),
                ],
                default="",
                max_length=32,
            ),
        ),
    ]
