# Generated by Django 4.2.14 on 2025-03-02 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_auto_20180918_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='session_key',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
