# Generated by Django 4.2.14 on 2026-05-02 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("adoorback", "0002_seed_missions"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Mission",
        ),
    ]
