# Generated by Django 4.2.14 on 2026-05-08 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adoorback", "0006_update_may_5_cta_url_to_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="mission",
            name="cta_label",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="mission",
            name="type",
            field=models.CharField(
                choices=[
                    ("song", "Song"),
                    ("question", "Question"),
                    ("text", "Text"),
                    ("compliment", "Compliment"),
                    ("none", "None"),
                ],
                max_length=20,
            ),
        ),
    ]
